import { Inter, Sora, Space_Grotesk, JetBrains_Mono } from "next/font/google";

import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import getCurrentUser from "../lib/getUser";
import { use } from "react";
import { createBulkPosts, deleteAllPosts } from "../lib/actions/post";
import { Toaster } from "@/components/ui/sonner";

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});
export const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
});
export const metadata = {
  title: "Developer Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  console.log("user:", user);
  return (
    <html
      lang="en"
      className={`${sora.variable} ${spaceGrotesk.variable} ${inter.variable} h-full scroll-smooth antialiased`}
    >
      <body className="relative min-h-full flex flex-col font-inter">
        <Header user={user} />
        {children}
        <Toaster
          richColors
          closeButton
          position="top-right"
          // toastOptions={{
          //   classNames: {
          //     toast: "bg-accent rounded-lg text-white",
          //   },
          // }}
        />
        <Footer />
        <div className="absolute bottom-4 left-4 flex gap-4 flex-col">
          <button
            onClick={createBulkPosts}
            className="font-sans font-medium tracking-wider py-2 px-4 bg-gray-100 hover:bg-gray-300 transition-all duration-200 text-black rounded-full my-2 active:scale-105"
          >
            ADD POSTS
          </button>
          <button
            onClick={deleteAllPosts}
            className="font-sans font-medium tracking-wider py-2 px-4 bg-accent hover:bg-hover transition-all duration-200 text-indigo-50 rounded-full my-2 active:scale-105"
          >
            DELETE ALL POSTS
          </button>
        </div>
      </body>
    </html>
  );
}
