import { Inter, Sora, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import getCurrentUser from "../lib/getUser";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";
import AccentProvider from "@/providers/AccentProvider";
import { SessionProvider } from "next-auth/react";

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});
export const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
});
export const metadata = {
  title: "Developer Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sora.variable} ${spaceGrotesk.variable} ${inter.variable} h-full scroll-smooth antialiased`}
    >
      <body className="relative min-h-full flex flex-col font-inter">
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AccentProvider>
              <Header user={user} />

              {children}
              <Toaster richColors closeButton position="top-center" />
              <Footer />
            </AccentProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
