import { Inter, Sora, Space_Grotesk, JetBrains_Mono } from "next/font/google";

import "./globals.css";

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});
export const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
});
export const metadata = {
  title: "Developer Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${spaceGrotesk.variable} ${inter.variable} h-full scroll-smooth antialiased`}
    >
      <body className="relative min-h-full flex flex-col font-inter">
        {children}
      </body>
    </html>
  );
}
